name: rag-chatbot
dependencies:
  - python=3.10
  - pip
  - pip:
      - ollama
      - langchain
      - langchain-community
      - chromadb
      - fastapi
      - streamlit
      - uvicorn
      - requests
      - unstructured
      - sentence-transformers
